---
- name: "Update/upgrade packages 1"
  become: yes
  apt:
    update_cache: yes

- name: "Update/upgrade packages 2"
  become: yes
  apt:
    upgrade: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Install nodejs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes


