---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: Creates directory in ubuntu
  become_user: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Transfer backend files from cloud server
  become: true
  copy:
    src: /etc/backend.tar.gz
    dest: /home/ubuntu/backend/backend.tar.gz
    owner: ubuntu
    
- name: Uncompress Backend
  shell: |
    cd /home/ubuntu/backend
    tar xvzf backend.tar.gz -C .
    ls -la

- name: "Insatll npm, dependencies, build package and start node"
  become: true
  shell: |
    cd /home/ubuntu/backend
    echo="############################# 1 ##########################"
    npm install -g npm@latest
    echo="############################# 2 ##########################"
    ls -la
    echo="############################# 3 ##########################"
    npm install
    echo="############################# 4 ##########################"
    npm audit fix --audit-level=critical --force
    echo="############################# 5 ##########################"
    npm run build
    echo="############################# 6 ##########################"
    pm2 start npm --name backend -- start
    echo="############################# 7 ##########################"
    pm2 ls
    echo="############################# 8 ##########################"

