- name: Creates directory in ubuntu
  become_user: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Transfer backend files from cloud server
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu/

- name: "Insatll npm, dependencies, build package and start node"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install -g npm@latest
    ls -la
    npm install
    npm audit fix --audit-level=critical --force
    npm run build
    pm2 start npm --name backend -- start
    pm2 ls
