version: 2.1

commands:
            
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Delete s3 bucket
          when: on_fail
          command: |
            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
            exit 0
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name prod-backend-${CIRCLE_WORKFLOW_ID:0:7}
            aws cloudformation delete-stack --stack-name prod-frontend-${CIRCLE_WORKFLOW_ID:0:7}

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    steps:
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            SUCCESS=$(curl -H "token: 8ceeeb81-69b3-4a0d-b8b8-a9e5eaa307c3" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7})
            if(( $SUCCESS==1 )); 
            then
              cd ~/project/backend
              npm install -g npm-check-updates
              npm run migrations:revert
            fi
jobs:
          
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: build-frontend
          command: |
            cd frontend
            npm install -g npm-check-updates 
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
          
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: test-frontend
          command: |
            cd frontend
            npm install -g npm-check-updates
            npm run test
            
  scan-frontend:      
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: scan-frontend
          command: |
            cd frontend
            npm install -g npm-check-updates
            npm audit fix --audit-level=critical --force

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: build-backend
          command: |
            cd backend
            npm install  -g npm-check-updates
            npm i
            npm run build
            npm audit fix --audit-level=critical --force
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
          
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: test-backend
          command: |
            cd backend
            sudo  npm  install oauth-sign
            sudo  npm run  test

             
  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: scan-backend
          command: |
            cd backend
            npm install -g npm-check-updates
            npm audit fix --audit-level=critical --force
            
#############################################

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: yum install -y tar gzip
      - run:
          name: installing other software
          command: |
            yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            yum install jq -y
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy --template-file .circleci/files/backend.yml --stack-name prod-backend-${CIRCLE_WORKFLOW_ID:0:7} --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} --tags project=prod-backend-${CIRCLE_WORKFLOW_ID:0:7} 

      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy --template-file .circleci/files/frontend.yml --stack-name prod-frontend-${CIRCLE_WORKFLOW_ID:0:7} --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} --tags project=prod-frontend-${CIRCLE_WORKFLOW_ID:0:7}

      - run:
          name: Add back-end ip to ansible inventory
          working_directory: ./.circleci/ansible
          command: |
            pwd &&
            ls -la
            echo "####################### 1 echo ######################################"
            aws ec2 describe-instances \
              --region us-east-2 \
              --query "Reservations[*].Instances[*].PublicIpAddress" \
              --filters "Name=tag:project,Values=prod-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --output text >> inventory.txt
            echo "####################### 2 echo ######################################"
            cat inventory.txt
            
           
      - run:
          name: Add back-end ip to memstash
          working_directory: ./.circleci/ansible
          command: |
            BACKEND=$(aws ec2 describe-instances \
              --region us-east-2 \
              --query "Reservations[*].Instances[*].PublicIpAddress" \
              --filters "Name=tag:project,Values=prod-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --output text )
            echo "####################### 1 echo ######################################"
            echo "${BACKEND}"
            echo "http://$BACKEND:3030"
            curl -H "Content-Type: text/plain" -H "token: 8ceeeb81-69b3-4a0d-b8b8-a9e5eaa307c3" --request PUT --data "$BACKEND" https://api.memstash.io/values/BACKENDURL

      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      - revert-migrations


  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["90:e7:17:fc:c1:bd:52:7c:8a:69:6c:54:e4:ac:65:4c"]
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip ansible nodejs npm
            apk add --no-cache python3 py3-pip && pip3 install --upgrade pip && pip3 install awscli && rm -rf /var/cache/apk/*
            /usr/local/bin/python -m pip install --upgrade pip
            apk add --update openssh-client
            apk add --update curl
            apk add --update jq
            
      - run:
          name: Configure server
          working_directory: ./.circleci/ansible
          command: |
            pwd &&
            ls -la
            cat inventory.txt
            ansible-playbook -i inventory.txt configure-server.yml
      - revert-migrations  
            
           ################
  run-migrations:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: awscli install
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3
            sudo apt-get -qq install awscli
      - run:
          name: envts
          working_directory: ./backend
          command: |
            touch .env
            echo ENVIROMENT=production > .env
            echo NODE_ENV=production >> ".env"
            echo TYPEORM_CONNECTION=postgres >> .env
            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> .env
            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> .env
            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> .env
            echo TYPEORM_HOST=$TYPEORM_HOST >> .env
            echo TYPEORM_PORT=$TYPEORM_PORT >> .env
            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .env
            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> .env
            ls -latr
            cat .env
      - run:
          name: Run migrations
          working_directory: ./backend
          command: |
            pwd
            echo "HOST: " $TYPEORM_HOST
            echo "PWD: " $(pwd)
            echo $TYPEORM_DATABASE
            npm install -g npm-check-updates
            npm run build
            npm audit fix --audit-level=critical --force
            touch run_migrations.txt
            npm run migrations:revert
            npm run migrations >> run_migrations.txt
            cat run_migrations.txt
      - run:
          name: Send migration results to memstash
          command: |
            #!/bin/bash
            pwd &&
            ls -la
            cd backend
            cat run_migrations.txt
            if [ $(grep -i "has been executed successfully" run_migrations.txt | wc -l) -ge 1 ]
            then
              echo "DB migration successful, updating memstash!!"
              curl -H "Content-Type: text/plain" -H "token: 8ceeeb81-69b3-4a0d-b8b8-a9e5eaa307c3" --request PUT --data "Migration Successful" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
            else
              echo "DB migration got failed."
              curl -H "Content-Type: text/plain" -H "token: 8ceeeb81-69b3-4a0d-b8b8-a9e5eaa307c3" --request PUT --data "Migration Failed" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
            fi
            echo "####################### 1 echo ######################################"
            SUCCESS=$(curl -H "token: 8ceeeb81-69b3-4a0d-b8b8-a9e5eaa307c3" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID})
            echo "####################### 2 echo ######################################"
            echo "${SUCCESS}" 
            echo "####################### 3 echo ######################################"
#      - save_cache:
#          paths: [backend/node_modules]
#          key: backend-build
      - revert-migrations  
      - destroy-environment

  deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum -y install tar gzip
            curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
            yum -y install nodejs
      - run:
          name: Get backend url and Build frontend
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances --region us-east-2 --query "Reservations[*].Instances[*].PublicIpAddress" --filters "Name=tag:project,Values=prod-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text )
            export API_URL="http://${BACKEND_IP}:3030"
            echo "${API_URL}" >> "frontend/.env"
            cat frontend/.env
            cd frontend
            npm install -g npm-check-updates
            npm run build
            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
      - run:
          name: Deploy frontend objects
          working_directory: ./frontend
          command: |
            aws s3 cp ./dist "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}" --recursive
      - revert-migrations  
      - destroy-environment     
                    
  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["90:e7:17:fc:c1:bd:52:7c:8a:69:6c:54:e4:ac:65:4c"]
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip ansible nodejs npm
            pip install awscli
            /usr/local/bin/python -m pip install --upgrade pip
            apk add --update openssh-client
            apk add --update curl
            apk add --update jq
      - run:
          name: Compress Backend
          command: |
            [[ ! -d backend ]] && mkdir backend
            ls -la
            echo "My current workspace is : $(pwd)"               
            myenv="backend/.env"
            echo ENVIROMENT=production > $myenv
            echo NODE_ENV=production >> $myenv
            echo TYPEORM_CONNECTION=postgres >> $myenv
            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> $myenv
            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> $myenv
            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> $myenv
            echo TYPEORM_HOST=$TYPEORM_HOST >> $myenv
            echo TYPEORM_PORT=$TYPEORM_PORT >> $myenv
            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> $myenv
            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> $myenv
            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> $myenv
            tar -C backend -czvf backendtar.tar.gz .
            ls -la
              
      - run:
          name: Deploy backend
          command: |
            ANSIBLE_HOST_KEY_CHECKING=False
            pwd
            pwd
            cd .circleci/ansible
            cat inventory.txt
            ANSIBLE_HOST_KEY_CHECKING=False 
            ansible-playbook -i inventory.txt deploy-backend.yml
            
      - revert-migrations  
      - destroy-environment 

  smoke-test:
    docker:
      - image: python:3.9.0-alpine 
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update curl 
            apk add --update tar 
            apk add --update gzip 
            apk add --update ansible 
            apk add --update nodejs 
            apk add --update npm
            pip install awscli
      - run:
          name: Backend smoke test
          command: |
            BKURL=$(curl -H "token: 8ceeeb81-69b3-4a0d-b8b8-a9e5eaa307c3" --request GET https://api.memstash.io/values/BACKENDURL)            
            echo "back end url :  http://$BKURL:3030/api/status"
            if curl -s "http://$BKURL:3030/api/status" | grep "ok"
            then
              echo "Backend alive, Proceeding"
            else
              exit 1
            fi
            
      - run:
          name: Frontend smoke test.
          command: |
            URL="https://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-us-east-2.amazonaws.com/index.html"
            echo "${URL}"
            if curl -s ${URL} | grep "Welcome"
            then
              return 0            
            else
              return 1
            fi
      - revert-migrations  
      - destroy-environment 

  cloudfront-update-and-cleanup:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
            yum -y install nodejs
            yum -y install tar gzip
            
      - run:
          name: get OldWorkflowID
          command: |
            export OldWorkflowID=$(aws cloudformation list-exports --query "Exports[?Name==\`WorkflowID\`].Value" --no-paginate --output text)
            echo "OldWorkflowID is : $OldWorkflowID"
            curl -H "Content-Type: text/plain" -H "token: 8ceeeb81-69b3-4a0d-b8b8-a9e5eaa307c3" --request PUT --data "${OldWorkflowID}" https://api.memstash.io/values/OldWorkflowID

      - run:
          name: cloudfront update-stack 
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/cloudfront.yml \
              --tags project=udapeople-cloudfront \
              --stack-name udapeople-cloudfront-prod \
              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" 

      - run:
          name: Cleanup
          command: |
            export OldWorkflowID=$(curl -H "Content-Type: text/plain" -H "token: 8ceeeb81-69b3-4a0d-b8b8-a9e5eaa307c3" --request GET https://api.memstash.io/values/OldWorkflowID)
            echo "OldWorkflowID is : $OldWorkflowID"

            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" --stack-status-filter CREATE_COMPLETE --no-paginate --output text))

            echo "STACKS @ : ${STACKS[@]}"
            echo "STACKS 0 : ${STACKS[0]}"
            echo "STACKS 1 : ${STACKS[1]}"
            echo "STACKS 2 : ${STACKS[2]}"
            echo "STACKS 3 : ${STACKS[3]}"
            echo "STACKS 4 : ${STACKS[4]}"
            
            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
            then   
               echo "${STACKS[@]} =~ ${OldWorkflowID} => Hence delete old workflowid"
               aws s3 rm s3://udapeople-${OldWorkflowID} --recursive
               aws cloudformation delete-stack --stack-name "prod-frontend-${OldWorkflowID}"
               aws cloudformation delete-stack --stack-name "prod-backend-${OldWorkflowID}"
             else
               echo "${STACKS[@]} == ${OldWorkflowID}  => Hence nothing need to be done here."
             fi

             
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          filters:
            branches:
              only: [master]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
          filters:
            branches:
              only: [master]
      - run-migrations:
          requires: [configure-infrastructure]
          filters:
            branches:
              only: [master]
      - deploy-backend:
          requires: [run-migrations]
          filters:
            branches:
              only: [master]
      - deploy-frontend:
          requires: [deploy-backend]
          filters:
            branches:
              only: [master]
      - smoke-test:
          requires: [deploy-backend, deploy-frontend]
          filters:
            branches:
              only: [master]
      -  cloudfront-update-and-cleanup:
          requires: [smoke-test]
          filters:
            branches:
              only: [master]